Time contingent
MetalCar/tv-childlock-control pull request #4
Opened 2020-04-02 11:38 UTC by hermann-p

2020-04-02 11:40 UTC, hermann-p commented on src/server/start.ts
> +        response.json(mkStatus);
```suggestion
        response.json(mkStatus());
```

2020-04-06 11:24 UTC, MetalCar requested changes
Ich finds geil :) Gerne noch die Routen ändern :) Testen werd ich das auch gleich mal ^^

2020-04-06 11:24 UTC, MetalCar commented on src/server/start.ts
> +  "/tv/timeLimit/on",
Ich fände es cooler, wenn wir die Routen lowercase halten könnten. Also wäre mir `timelimit` oder `time-limit` lieber.

2020-04-06 11:24 UTC, MetalCar commented on src/server/start.ts
> +  "/tv/timeLimit/off",
Ich fände es cooler, wenn wir die Routen lowercase halten könnten. Also wäre mir `timelimit` oder `time-limit` lieber.

2020-04-07 06:09 UTC, hermann-p commented on src/server/start.ts
> +  "/tv/timeLimit/on",
```suggestion
  "/tv/time-limit/on",
```

2020-04-07 06:09 UTC, hermann-p commented on src/server/start.ts
> +  "/tv/timeLimit/off",
```suggestion
  "/tv/time-limit/off",
```

2020-04-07 15:06 UTC, MetalCar approved these changes

2020-04-07 15:08 UTC, merged